/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session Info
         * @description Who is signed in, so the web app shows the presenter's overlay to admins only
         *     (D3-4, BD-41). 401 without a valid session.
         */
        get: operations["session_info_api_v1_session_get"];
        put?: never;
        /** Start Session */
        post: operations["start_session_api_v1_session_post"];
        /** End Session */
        delete: operations["end_session_api_v1_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description Liveness for the platform (BD-25): the process answers and Postgres, the only
         *     store without which nothing works, is reachable. A Neo4j or Qdrant restart degrades
         *     /health but must not make the platform restart the app and kill a run.
         */
        get: operations["live_api_v1_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cities/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve */
        post: operations["resolve_api_v1_cities_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Run */
        post: operations["start_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Events */
        get: operations["run_events_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Slots
         * @description The 16 questions every run answers, for the live coverage grid (D3-4, BD-41).
         */
        get: operations["slots_api_v1_slots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Cities
         * @description "Open existing": every city with a finished run, the newest first (AT-25, AT-37).
         */
        get: operations["list_cities_api_v1_cities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cities/{city_id}/brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Brief
         * @description The city's latest run as a brief (LLD-4 §3.3): stored knowledge, no new research
         *     (AT-25), with the date it is as of.
         */
        get: operations["brief_api_v1_cities__city_id__brief_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cities/{city_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Findings
         * @description FactCards of the latest run, filtered. When a filter keeps one side of a
         *     disagreement, the other side comes with it.
         */
        get: operations["findings_api_v1_cities__city_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cities/{city_id}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Entities
         * @description Entities named by the latest run's facts, by type, with how many facts name them.
         */
        get: operations["entities_api_v1_cities__city_id__entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cities/{city_id}/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Entity
         * @description The entity and its one-hop edges from the knowledge graph (non-negotiable 5). Each
         *     edge's claims are checked again in Postgres: only confirmed claims of the latest run,
         *     or ones a newer claim ended, keep an edge (LLD-5 re-validation).
         */
        get: operations["entity_api_v1_cities__city_id__entities__entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facts/{claim_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence */
        get: operations["evidence_api_v1_facts__claim_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshots/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Snapshot
         * @description The bytes as retrieved, whatever the live page says now (R-55, AT-27).
         */
        get: operations["snapshot_api_v1_snapshots__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cities/{city_id}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_v1_cities__city_id__ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/answers/{answer_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Answer Trace
         * @description The stored retrieval trace of one answer (LLD-5 §10; DS-5 "why this answer").
         */
        get: operations["answer_trace_api_v1_admin_answers__answer_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cities/{city_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report */
        get: operations["report_api_v1_cities__city_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflow/diagram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diagram */
        get: operations["diagram_api_v1_workflow_diagram_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerSentenceOut */
        AnswerSentenceOut: {
            /** Text */
            text: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "fact" | "mention" | "analysis" | "abstain";
            /** Refs */
            refs: string[];
            main_badge: components["schemas"]["BadgeCard"] | null;
            /** Status Word */
            status_word: string | null;
            /** Slot Id */
            slot_id: string | null;
        };
        /** AnswerTraceResponse */
        AnswerTraceResponse: {
            /** Answer Id */
            answer_id: string;
            /** Question */
            question: string;
            /** Trace */
            trace: {
                [key: string]: unknown;
            };
        };
        /** AskOptions */
        AskOptions: {
            /**
             * Graph
             * @default on
             * @enum {string}
             */
            graph: "on" | "off";
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
            options?: components["schemas"]["AskOptions"];
            /** Conversation Id */
            conversation_id?: string | null;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer Id */
            answer_id: string;
            /** Question Type */
            question_type: string;
            /** Sentences */
            sentences: components["schemas"]["AnswerSentenceOut"][];
            /** Graph Used */
            graph_used: boolean;
            /** Run Id */
            run_id: string;
            /** Conversation Id */
            conversation_id: string;
            /** Turn */
            turn: number;
            /** Trace */
            trace?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * Badge
         * @description Declaration order is severity, most severe first (R-78).
         * @enum {string}
         */
        Badge: "not_city_level" | "sources_disagree" | "outdated" | "limited_sample";
        /** BadgeCard */
        BadgeCard: {
            /** Code */
            code: string;
            /** Label */
            label: string;
        };
        /** BriefResponse */
        BriefResponse: {
            /** City */
            city: {
                [key: string]: unknown;
            };
            run: components["schemas"]["BriefRun"];
            /** Summary */
            summary: {
                [key: string]: components["schemas"]["FactCard"][];
            };
            /** Coverage */
            coverage: components["schemas"]["SlotRow"][];
            /** Handle With Care */
            handle_with_care: components["schemas"]["CareItem"][];
            /** Counts */
            counts: {
                [key: string]: unknown;
            };
        };
        /** BriefRun */
        BriefRun: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /**
         * CareItem
         * @description A fact to read with care, and why (LLD-2 §16.6).
         */
        CareItem: {
            card: components["schemas"]["FactCard"];
            /** Reason */
            reason: string;
        };
        /** CitiesResponse */
        CitiesResponse: {
            /** Items */
            items: components["schemas"]["CityItem"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** CityItem */
        CityItem: {
            /** City Id */
            city_id: string;
            /** Name */
            name: string;
            /** Country Name */
            country_name: string;
            /** Latest Run Id */
            latest_run_id: string;
            /** Latest Run At */
            latest_run_at: string | null;
            /** Latest Run Status */
            latest_run_status: string;
        };
        /**
         * ClaimStatus
         * @enum {string}
         */
        ClaimStatus: "extracted" | "dropped" | "supported" | "refuted" | "insufficient" | "contested" | "superseded";
        /** ComponentHealth */
        ComponentHealth: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "down" | "not_loaded" | "not_configured";
            /** Latency Ms */
            latency_ms?: number | null;
            /** Slots */
            slots?: number | null;
        };
        /** ConfidenceCard */
        ConfidenceCard: {
            /** Label */
            label: string;
            /** Label Word */
            label_word: string;
            /** Points */
            points: number;
            /** Reasons */
            reasons: components["schemas"]["ReasonCard"][];
            /** Capped By */
            capped_by?: string | null;
        };
        /** ConsistencyOut */
        ConsistencyOut: {
            /** Outcome */
            outcome: string;
            /** Compared With */
            compared_with: string[];
            /** Reason */
            reason: string;
        };
        /** ContestedPair */
        ContestedPair: {
            /** Headline Claim Id */
            headline_claim_id: string;
            /** Other Claim Id */
            other_claim_id: string;
        };
        /**
         * DiagramResponse
         * @description Mermaid text of the compiled graphs (LLD-4 §3.5, AT-03).
         */
        DiagramResponse: {
            /** Main */
            main: string;
            /** Slot */
            slot: string;
        };
        /** EntitiesResponse */
        EntitiesResponse: {
            /** By Type */
            by_type: {
                [key: string]: components["schemas"]["EntityItem"][];
            };
        };
        /** EntityEdgeOut */
        EntityEdgeOut: {
            /** Relation */
            relation: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "outgoing" | "incoming";
            other_entity: components["schemas"]["OtherEntity"];
            /** Valid From */
            valid_from: string | null;
            /** Valid To */
            valid_to: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "current" | "ended" | "contested";
            /** Claim Ids */
            claim_ids: string[];
        };
        /** EntityItem */
        EntityItem: {
            /** Entity Id */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            /** Name */
            name: string;
            /** Facts */
            facts: number;
        };
        /** EntityResponse */
        EntityResponse: {
            entity: components["schemas"]["EntityItem"];
            /** Attributes */
            attributes: {
                [key: string]: unknown;
            };
            /** Edges */
            edges: components["schemas"]["EntityEdgeOut"][];
            /** Graph Used */
            graph_used: boolean;
        };
        /** EvidenceResponse */
        EvidenceResponse: {
            card: components["schemas"]["FactCard"];
            /** Quote */
            quote: string;
            /** Quote Lang */
            quote_lang: string;
            /** Quote Translation */
            quote_translation: string | null;
            passage: components["schemas"]["Passage"] | null;
            /** Label Passages */
            label_passages: {
                [key: string]: string;
            };
            /** Geography Fit */
            geography_fit: {
                [key: string]: unknown;
            } | null;
            verdict: components["schemas"]["VerdictOut"] | null;
            snapshot: components["schemas"]["SnapshotOut"] | null;
            consistency: components["schemas"]["ConsistencyOut"] | null;
        };
        /** FactCard */
        FactCard: {
            /** Claim Id */
            claim_id: string;
            /** Slot Id */
            slot_id: string;
            /** Kind */
            kind: string;
            /** Statement */
            statement: string;
            /** Value As Written */
            value_as_written: string | null;
            geography: components["schemas"]["GeographyCard"];
            period: components["schemas"]["PeriodCard"];
            population: components["schemas"]["PopulationCard"];
            /** Status */
            status: string;
            /** Status Word */
            status_word: string;
            main_badge: components["schemas"]["BadgeCard"] | null;
            /** Other Badges */
            other_badges: components["schemas"]["BadgeCard"][];
            confidence: components["schemas"]["ConfidenceCard"] | null;
            source: components["schemas"]["SourceCard"];
        };
        /** FindingsResponse */
        FindingsResponse: {
            /** Items */
            items: components["schemas"]["FactCard"][];
            /** Contested */
            contested: components["schemas"]["ContestedPair"][];
            /** Slots */
            slots: components["schemas"]["SlotRow"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** GeographyCard */
        GeographyCard: {
            /** Level */
            level: string;
            /** Level Word */
            level_word: string;
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Checked At */
            checked_at: string;
            /** Components */
            components: {
                [key: string]: components["schemas"]["ComponentHealth"];
            };
            /**
             * Checker Independence
             * @enum {string}
             */
            checker_independence: "different_family" | "same_family_allowed";
            /** Versions */
            versions: {
                [key: string]: string;
            };
            /** Resume */
            resume?: ("on" | "off") | null;
        };
        /** OtherEntity */
        OtherEntity: {
            /** Entity Id */
            entity_id: string | null;
            /** Entity Type */
            entity_type: string;
            /** Name */
            name: string;
        };
        /** Passage */
        Passage: {
            /** Text */
            text: string;
            /** Highlight Start */
            highlight_start: number;
            /** Highlight End */
            highlight_end: number;
        };
        /** PeriodCard */
        PeriodCard: {
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            /** Type */
            type: string;
            /** Stated */
            stated: boolean;
        };
        /** PlaceCandidate */
        PlaceCandidate: {
            /** Gazetteer Id */
            gazetteer_id: string;
            /** Name */
            name: string;
            /** Admin1 Name */
            admin1_name: string | null;
            /** Country Name */
            country_name: string;
            /** Country Iso2 */
            country_iso2: string;
            /** Population */
            population: number | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
        };
        /**
         * PopulationCard
         * @description Who the figure is about (AT-14; BD-37): a sub-population shows here, flagged.
         */
        PopulationCard: {
            /** Age Min */
            age_min: number | null;
            /** Age Max */
            age_max: number | null;
            /** Sex */
            sex: string;
            /** Group */
            group: string | null;
            /** Subgroup */
            subgroup: boolean;
        };
        /** ReasonCard */
        ReasonCard: {
            /** Component */
            component: string;
            /** Points */
            points: number;
            /** Note */
            note: string;
        };
        /** ResolveRequest */
        ResolveRequest: {
            /** Query */
            query: string;
        };
        /** ResolveResponse */
        ResolveResponse: {
            /** Exact */
            exact: boolean;
            /** Candidates */
            candidates: components["schemas"]["PlaceCandidate"][];
        };
        /** RunResponse */
        RunResponse: {
            /** Run Id */
            run_id: string;
            /** City Id */
            city_id: string;
            /** Status */
            status: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Summary */
            summary: {
                [key: string]: unknown;
            } | null;
            /** Versions */
            versions: {
                [key: string]: string;
            };
        };
        /** SessionInfo */
        SessionInfo: {
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "admin";
            /** Expires At */
            expires_at: number;
        };
        /** SessionRequest */
        SessionRequest: {
            /** Access Code */
            access_code: string;
        };
        /** SlotInfo */
        SlotInfo: {
            /** Slot Id */
            slot_id: string;
            /** Dimension */
            dimension: string;
            /** Question */
            question: string;
            /** Short Label */
            short_label: string;
            /** Headline */
            headline: boolean;
        };
        /** SlotRow */
        SlotRow: {
            /** Slot Id */
            slot_id: string;
            /** Dimension */
            dimension: string;
            /** Question */
            question: string;
            /** Headline */
            headline: boolean;
            /** Status */
            status: string;
            /** Status Word */
            status_word: string;
            /** Flags */
            flags: string[];
            /** Gap Note */
            gap_note: string | null;
            /** Best Claim Ids */
            best_claim_ids: string[];
            /** Queries */
            queries: number;
            /** Sources */
            sources: number;
            /** Replans Used */
            replans_used: number;
        };
        /** SnapshotOut */
        SnapshotOut: {
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Content Type */
            content_type: string;
            /** Url */
            url: string;
        };
        /** SourceCard */
        SourceCard: {
            /** Source Id */
            source_id: string;
            /** Publisher Class */
            publisher_class: string;
            /** Title */
            title: string | null;
            /** Url */
            url: string;
            /** Published Date */
            published_date: string | null;
            /** Retrieved At */
            retrieved_at: string;
        };
        /** StartRunRequest */
        StartRunRequest: {
            /** Gazetteer Id */
            gazetteer_id: string;
        };
        /** StartRunResponse */
        StartRunResponse: {
            /** Run Id */
            run_id: string;
            /** City Id */
            city_id: string;
            /** Status */
            status: string;
            /** Events Url */
            events_url: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerdictOut */
        VerdictOut: {
            /** Label */
            label: string;
            /** Rationale */
            rationale: string;
            /** Model */
            model: string;
            /** Fallback Used */
            fallback_used: boolean;
            /** Checker Prompt */
            checker_prompt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    session_info_api_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
        };
    };
    start_session_api_v1_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_session_api_v1_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    live_api_v1_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    resolve_api_v1_cities_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "last-event-id"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    slots_api_v1_slots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotInfo"][];
                };
            };
        };
    };
    list_cities_api_v1_cities_get: {
        parameters: {
            query?: {
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CitiesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brief_api_v1_cities__city_id__brief_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                city_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    findings_api_v1_cities__city_id__findings_get: {
        parameters: {
            query?: {
                dimension?: string | null;
                slot?: string | null;
                status?: components["schemas"]["ClaimStatus"] | null;
                badge?: components["schemas"]["Badge"] | null;
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path: {
                city_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entities_api_v1_cities__city_id__entities_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                city_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitiesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entity_api_v1_cities__city_id__entities__entity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                city_id: string;
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_api_v1_facts__claim_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_api_v1_snapshots__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_v1_cities__city_id__ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                city_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_trace_api_v1_admin_answers__answer_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                answer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerTraceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_api_v1_cities__city_id__report_get: {
        parameters: {
            query?: {
                format?: "md" | "html" | "pdf";
            };
            header?: never;
            path: {
                city_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diagram_api_v1_workflow_diagram_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagramResponse"];
                };
            };
        };
    };
}
